### ISSUE TITLE
Seeking Guidance for mfe'ing services and model ts implementations.

### ISSUE THREAD

**Issue by curiousdev** [angular-architects/module-federation-plugin#109]
I am trying to figure out to MFE's a service.ts. Any guidance would be appreciated?

In MFE1,

```
plugins: [
    new ModuleFederationPlugin({
        name: "mfe1",
        filename: "remoteEntry.js",
        exposes: {
            './PricingService': '/projects/mfe1/src/app/pricing.service.ts'
        },
        ...
```

How does the app/shell import the service? Most examples, I see relate to a route-based lazy load.

**Comment by curiousdev** [comment]
Motivation is to ship common-services in their own mfe js artifact.

**Comment by manfredsteyer** [comment]
Good question!

If you just expose the service, it's like lazy loading a class. To make it work with DI, you need a provider. You could register the service in a NgModule, load this NgModule via MF, instantiate it with Angular. This gives you an injector you can use by hand in order to access the service and resolve its dependencies. 

My friend Juri writes about this here:
https://juristr.com/blog/2019/10/lazyload-module-ivy-viewengine/

You just need to extend this example by MF/ by using paths mapped via MF.

Best wishes,
Manfred
