### ISSUE TITLE
Migration Guide for Angular 13 ("target": "es2020")

### ISSUE THREAD

**Issue by houdass** [angular-architects/module-federation-plugin#144]
Hello world,

Thanks a lot for your migration guide for Angular 13 & MF, very helpful.

I was wondering if changing the compilation target to es2020 in tsconfig.json can be problematic in supporting old browser versions (chrome, Firefox, Edge …) and especially IOS Safari? Also, why it is mandatory to change it to this specific version, what is the benefit? By checking the compatibility table and the features of es2020 here: https://kangax.github.io/compat-table/es2016plus/ I don't see what's make MF work with ES2020 and not the previous ES versions.

By keeping a lower version of es in target (tested with es2017, es2018 and es2019), I got the following error:

main.js:1 ERROR Error: Uncaught (in promise): Error: Automatic publicPath is not supported in this browser
Error: Automatic publicPath is not supported in this browser
at entry.js:1:1088511
The weird part, is that the publicPath: 'auto' was working fine for me with a MF and Angular 12.

Thanks a lot.

**Comment by manfredsteyer** [comment]
We haven't seen any issue with it so far. 

The reason is that esbuild -- now used by the CLI together with webpack for optimizing the bundles -- is not emitting the code we need for publicPath:'auto' (mata.import) if the target is lower then es2020.

It was working with Angular 12 b/c Angular <= 12.x emits "normal" javascript bundles. Angular >= 13, however, emits EcmaScript modules and to find out the current path of them for publicPath:'auto' we need meta.import.

It also seems like the next versions of Angular will use es2020 by default.
