### ISSUE TITLE
Is it possible to inject the webpack.config.js at runtime?

### ISSUE THREAD

**Issue by shuppert** [angular-architects/module-federation-plugin#149]
I have a scenario where I need the ability to adjust the shared library configuration on the server where it's deployed rather than at build time.  Is is possible to inject the webpack config dynamically at runtime?

**Comment by LoaderB0T** [comment]
The webpack config is used during the build, not at runtime. If you talk about configuring stuff like the shared modules or packages, that is not possible at runtime but has to be configured for the build.
Webpack has to know which parts of the app have to be written to a separate bundle at build time.
Basically, all webpack does here is cutting your bundle into pieces based on this plugin's config. So that at runtime webpack can decide which of those parts have to be loaded and which are already loaded. But the pieces have to be known at build time, so the config is used during build time.

You can however dynamically **load** modules that have been compiled with a compatible webpack config at runtime.

**Comment by manfredsteyer** [comment]
+1 
also see: https://www.angulararchitects.io/en/aktuelles/dynamic-module-federation-with-angular/
