### ISSUE TITLE
Feature Request: Single SPA integration

### ISSUE THREAD

**Issue by JSMike** [angular-architects/module-federation-plugin#236]
Hi Manfred,

We spoke at the end of NgConf. I was just at the EnterpriseNG summit yesterday and we were talking about MFE / Module Federation. One pain point that was discussed with the @angular-architects solution is that any non-angular applications need to be wrapped as web components. One thought I had, which is more theoretical, is if this plugin would be capable of integrating directly with components from other frameworks if they're setup with Single SPA to have a bootstrap function which can get called after it's added to the view. I'm interested in hearing your thoughts / feedback.

Thank you,
Mike Cebrian

**Comment by AlonsoK28** [comment]
Hi @JSMike first of all I would like to send you a greeting and I take the liberty of asking you a brief question about the use of the `ng/module-federation-plugin` library.

Basically it is the development of some `microfrontends` using `Angular 14+` to use it in a `mpa legacy application` made with `PHP + Webpack 5` (pure webpack + vanilla js), which I am trying to develop some more advanced features using `Angular Material` like a shopping cart and other necessary components.

Because of this I am considering the possibility of developing these microfronts using `module federation plugin` and consuming them in the `host app` via `webpack federated modules`

The biggest question is to know if it is necessary to use an intermediary library such as [`single-spa`](https://single-spa.js.org/) to be able to load the `mf module` in my `host app`, since I am currently using something like the following syntax to consume the `mfe module` from an `angular host app`:

```example.ts

```

Due to this I am not sure how I can communicate “webpack 5” with angular to tell it to carry out the instructions for the generation of the “component” and his corresponding “module” in order to show the “dialog material” over my “host app”, since I observe that I need to use of some “angular core” functions such as:

**Comment by JSMike** [comment]
Hi @AlonsoK28,

Busy week, I'll come up with a more detailed reply later.

For some quick context, our immediate use case would be for routing to non-angular components that have single-spa implementation. And to leverage module federation for dynamic loading, and resource sharing.

One of my coworkers was able to do this using a simple angular component wrapper that called the single-spa bootstrap function of a child Elm component. I was looking to have a more declarative configuration way to do this instead of having to write angular wrappers every time we want to use a component from another framework.

**Comment by manfredsteyer** [comment]
There are no official plans for this on our side.
