### ISSUE TITLE
Support for library projects

### ISSUE THREAD

**Issue by remye06** [angular-architects/module-federation-plugin#243]
Is there a way to use a library instead of an application Angular project in order to create a micro-frontend ?
My use case doesn't need routes and only instanciates mf elements via `viewContainerRef.createComponent`, so I don't need index.html etc.

**Comment by faileon** [comment]
I haven't worked with this repo yet, but if you can get a hold of the NgModule class by the loader, you can get to the components of the module. See https://github.com/alexzuza/angular-plugin-architecture-with-module-federation/issues/3#issuecomment-1293659024

**Comment by dkhrunov** [comment]
Hello, you can try using this library [ngx-mfe](https://github.com/dkhrunov/ngx-mfe#display-mfe-in-html-template--plugin-based-approach).
It is allows MFE components to be displayed directly inside the template (html) using the `*mfeOutlet=""` structural directive.

**Comment by manfredsteyer** [comment]
This will very like not work with Angular + Module Federation as the CLI does not use webpack for libs. Hence, you need an app that might be just a thin wrapper.

**Comment by remye06** [comment]
Thanks @manfredsteyer for making this clear.

**Comment by restjohn** [comment]
@manfredsteyer I am not well-enough versed in the Angular build system to know this immediately.  Would bundling an Angular library with Webpack make sense in order to accommodate module federation, and would that be viable as an integration to the library build chain?  Prior to Angular 13, when ng-packagr generated UMD modules, I was able to load libraries as MFEs with SystemJS at runtime.  Now that ng-packagr only produces FESM, I'm trying to apply the Module Federation Plugin, but now realizing that MFP expects the MFE projects to be applications, not libraries.  That's a bit counterintuitive to me, as my remote modules are intended only to be plugins for the host app, and not stand on their own.
