### ISSUE TITLE
Angular app not rendering in Safari browser

### ISSUE THREAD

**Issue by RajatSomani13** [angular-architects/module-federation-plugin#249]
When using the module federation plugin, the safari browser shows a blank screen. Works fine on all other browsers, please help as this is blocking our production deployment.

**Comment by ezagdir** [comment]
@RajatSomani13 It could be something with your setup rather than this plugin (which is just beautiful imho) I just want to drop my 2 cents here - in my project we have `@angular 14.2.2` with `@angular-architects/module-federation v14.3.10` and it works fine on Safari, but by previous experience with Safari shows that it crashed (blank screen) when I had circular dependencies across projects or imports were going outside the workspace boundaries (like in `../../../../libs/my-lib/`)

**Comment by RajatSomani13** [comment]
@ezagdir - Basis your suggestion, I don't see any circular dependency or imports going out of workspace boundaries. So not sure where I am going wrong. I have been able to narrow down the issue to the method sharedMappings.getDescriptors(), if I remove that then the application loads on safari but the library is not shared anymore.

**Comment by 2-Dpot** [comment]
@ezagdir  Facing the same issue and it's a blocker.  No issues in cross imports either.  And for config , i have a simple config in shell 
withModuleFederationPlugin({  
     {        
         name: 'xyz', 
         shared: share({@angual/core: ......}),
         sharedMappings: [..abc]
    } 
})

**Comment by 2-Dpot** [comment]
The issue was related to **wrong imports** . This has more to do with the angular side and not with  the plugin.
Thanks everyone !
