### ISSUE TITLE
Adding a Kendo Grid breaks Module Federation with @angular/localize error

### ISSUE THREAD

**Issue by ashwini-yenmakaje** [angular-architects/module-federation-plugin#287]
Hi,

I am facing the below issue while using kendo grid in both shell and mfe angular application.

node_modules_angular_material_fesm2020_tree_mjs-_9d740.js:1 ERROR Error: It looks like your application or one of its dependencies is using i18n.
Angular 9 introduced a global `$localize()` function that needs to be loaded.
Please run `ng add @angular/localize` from the Angular CLI.
(For non-CLI projects, add `import '@angular/localize/init';` to your `polyfills.ts` file.

After run the below command 
ng add @angular/localize
and adding `import '@angular/localize/init';` to `polyfills.ts` file also throws same issue.

Angular Version: 15
"@angular-architects/module-federation": "^15.0.3"
"ngx-build-plus": "^15.0.0",
"@progress/kendo-angular-grid": "^11.1.0",

Kindly let me know is there any additional configuration required for this.

**Comment by manfredsteyer** [comment]
This somehow rings a bell. Can you please try to add `@angular/localize` and `@angular/localize/init` to the skip array in your webpack.config?

**Comment by ashwini-yenmakaje** [comment]
Hi @manfredsteyer ,

Could you please elaborate?

Additionally, I have added a git repo of the demo project. Please look into it.

[https://github.com/ashwini-y/Module-Federation-Example/tree/master](url)

**Comment by manfredsteyer** [comment]
Hi,

please don't share ``@angular/localize/init`` nor ``@angular/localize`` in your ``webpack config``. If you use ``shareAll``, you can exclude them via skip:

```javascript
module.exports = withModuleFederationPlugin({

  name: 'myFirstApp',

  exposes: {
    './Module': './projects/my-first-app/src/app/manage-business-unit/manage-business-unit.module.ts',
  },

  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },

  skip:['@angular/localize/init', '@angular/localize']

});
```

Also, you need to add ``@angular/localize/init`` to your ``polyfills`` section in your ``angular.json``:

```javascript
"polyfills": [
	"zone.js",
	"@angular/localize/init"
],
```

Since some versions, this is the replacement for the ``polyfills.ts``.

If for some reason, the polyfills.ts is still loaded, make sure it's not imported there too.

Please find a working version of your example here:
https://github.com/manfredsteyer/2023_02_26.git
