### ISSUE TITLE
How can an angular remote use a service from the host

### ISSUE THREAD

**Issue by hersonls** [angular-architects/module-federation-plugin#353]
Hello everyone, I have a doubt that I thought it was possible to implement.

I have 2 repositories, one for the host and one for the remote, completely separate. Is it possible for the remote, loaded inside the host, to use angular services such as a Loading component, without using a library that is shared between the two?

We don't use monorepo, so the remote doesn't access files or know components shared by the host.

Sorry to send questions here, but I couldn't find a place to send them.

**Comment by IanWangTaiwan** [comment]
i have same problem 
how can i get the singleton instance don't with monorepo 
any idea?

**Comment by vmagalhaes** [comment]
In the scenario that I worked for, we created a Dockerfile running the host and the host has the remote configuration pointing to the locahost, and so we can work with this shared data

**Comment by manfredsteyer** [comment]
If you put the DI-Token in a shared lib, the remote can request the service registered for it.

**Comment by hersonls** [comment]
Thanks @manfredsteyer It worked very well. For people in the future with the same question, here is a simple example:

In your **HOST** app module, create a provider with a custom token:

```typescript
@NgModule({
  // ...
  providers: [
    {
      provide: 'AUTH_SERVICE',
      useExisting: AuthService,
    },
  ],
  // ...
  bootstrap: [AppComponent],
})
export class AppModule {}
```

In your **REMOTE**, you can inject with `@Inject`:

```typescript
constructor(
    private cdsLoadingService: CdsLoadingService,
    @Inject('AUTH_SERVICE') public authService: any,
  ) {
    console.log(authService);
  }
  ```

Remember to use typing correctly, instead of using `:any`

**Comment by Krishna4197** [comment]
Hi @hersonls , 
When we are using Module Federation approach, with multiRepo, 
1. Exposure of AuthService is sufficient from Host App or Host App's App.module.ts needs to be exposed as InjectionToken in provided there.
2. Following your solution, as 'AUTH_SERVICE' is not provided in REMOTE , its throwing error stating NullInjectorError: No provider for InjectionToken AUTH_SERVICE!.

3. If I provide  providers: [
    {
      provide: 'AUTH_SERVICE',
      useExisting: AuthService,
    },
  ],  
same in REMOTE app.module.ts --> its working but its creating a new instance rather than existing one. REMOTE1 and REMOTE2 are getting two separate instances of AuthService if provided in respective app.module.ts . If not provided NULLINJECTOR is throwing.

HOW TO SOLVE THESE
