### ISSUE TITLE
Is Native Federation "forwards compatible"?

### ISSUE THREAD

**Issue by refactorTractor** [angular-architects/module-federation-plugin#390]
Hi!

I'm considering introducing your package to a large enterprise ecosystem, with many independently deployable apps running on a platform.

I understand native federation makes the host and remotes independent of each other and their dependencies, and even their bundlers. You call native federation "future proof" on that basis. However your package is kind of new and angular doesn't even fully support esbuild yet (though that's the bundler you made examples with). Although all these microfrontends are independent, they'll still depend on using the same version of native federation, won't they? Or at least "compatible" versions of it. What are the outlooks in that regards? Can it be expected that the output of current native federation will play nicely with future versions (to the extent that underlying technology - browser API allows)? It seems like your development API is solid, since it's been kept from module federation. Can the output for this package be considered forward compatible in any matter as well?

**Comment by AGreat1** [comment]
Hi!

Thanks for the info. I would like to clarify. In other words, native federation is a library that creates an import map from a manifest. Developers are given API to use this import map (manifest, import, etc). Adapters to the bundlers are to ensure that the generated bundles are ESM modules or a collection of them. You ensure your API is stable, and ESM modules and import maps are also stable to the extent browsers support them. There is nothing in native federation that could cause runtime problems between bundles, because the interface between bundles if fully browser-native. Correct? If so, this is awesome and you may close this issue. Kudos to you and your team!

**Comment by manfredsteyer** [comment]
Yes. Honestly, Native Federation only has dynamic federation. Even though we use it in a way that looks like static federation, dynamic federation is used underneath the covers.
