### ISSUE TITLE
Package sharing for axios does not work

### ISSUE THREAD

**Issue by julianlumets** [angular-architects/module-federation-plugin#453]
Hi team!

I tried to install axios using `npm install axios`
I set everything up but then when i ran ng server - it failed.

The reason why it failed is that some references that axios uses ('http' for instance) could not be found / shared or something.

I will try to provide images from the exact error, but you can also easily try it by yourself.

Greets from upper austria

**Comment by manfredsteyer** [comment]
Hi Julian,

thanks for pointing this out.

It seems like the `adapter` entry point defined in axios' `package.json` uses libs that are not necessarily installed. Normally, this is not a big issue, because code not used is usually ignored. Native Federation, however, creates a ESM bundle for every entry point. And when compiling the `adapters` entry point it fails due to missing deps. 

One option is to install the missing deps; another one is to skip such not-used entry points. For this, you can also use a RegExp in your `skip` list:

skip: [
  'rxjs/ajax',
  'rxjs/fetch',
  'rxjs/testing',
  'rxjs/webSocket',
  /^axios\/.*?\/adapters/
  // Add further packages you don't need at runtime
]
