### ISSUE TITLE
Native Federation and SSR

### ISSUE THREAD

**Issue by Marbulinek** [angular-architects/module-federation-plugin#466]
Hello,
do you consider also support of SSR for native federation?
Nowadays there is some kind of build error, when trying to prerender routes. Also node server is not correctly linking remote links to MFE.
Thanks for answer :)

**Comment by manfredsteyer** [comment]
Yes, I have a blog article about that in the pipeline.

A solution that works immediately is using a wrapper component that loads the MFE for the client and the respective HTML fragment via HTTP on the server-side. This is, e. g., what IKEA is doing.

**Comment by rpanadero** [comment]
Sorry @manfredsteyer, could you explain it deeply? What do you mean when you say: "the respective HTML fragment via HTTP on the server side"? Thanks in advance!

**Comment by Marbulinek** [comment]
@manfredsteyer, @rpanadero 

This is what I discovered:
 - instead of route linking (and preparing module with components) - we need to use wrapper component directly.
 - inside this wrapper component, we are able to load mfe component dynamically:
 
 ```typescript
  @ViewChild('placeHolder', { read: ViewContainerRef }) viewContainer!: ViewContainerRef;

   ngOnInit() {
    if (isPlatformBrowser(this.platformId)) {
      // Client only code
      this.loadComponent().then(() => {
        console.log('Dynamically loaded component');
      });
    }else if(isPlatformServer(this.platformId)){      
      // Server only code.
      // Somehow load the component
      // Probably we need to run SSR also on MFE. And somehow link it here.
      // I dont know if some server libraries should be linked also or not. This should be awesome to have.
    }
  }

  async loadComponent(): Promise<void> {
      await loadRemoteModule('remote', './remoteHomeComponent').then((m) => {
        this.viewContainer.createComponent(m.HomeComponent);
      });
  }
```

But there are also other questions like: if we are going instead of module loading use the component loading (like in the code above) on the wrapper page, we are not able to use functionality linked to modules, like e.g.:

I want to use ngx-translate, where the definition of locale files is included in the module.
```typescript
  imports: [
    CommonModule,
    HttpClientModule,
     RouterModule.forChild(routes), 
     TranslateModule.forChild({
       extend: true,
       isolate: false,
       loader: {
           provide: TranslateLoader,
           useFactory: (http: HttpClient) => {
             return new TranslateHttpLoader(http, './assets/remote/localize/i18n/v1/', '.json');
           },
           deps: [HttpClient]
       }
    })
  ],
```

**Comment by manfredsteyer** [comment]
Hi @Marbulinek,

Yes, this is the solution. Instead of running Native Federation on the server side, you could also use the HttpClient to fetch the respective HTML fragment from the Micro Frontend and embed it.

Regarding NgModules: You can also load a whole module via import. Here is a short example:
https://developapa.com/angular-inline-lazy-load/

Best,
Manfred

**Comment by PaulDMooney** [comment]
Is there a solution, or a plan for a solution for supporting the route based lazy loading for SSR?

For example in my host/shell application I have a route defined:

```typescript
export const routes: Routes = [
  {
    path: 'remote-path',
    loadChildren: () => loadRemoteModule('mfe1', './PathOneRoutes')
        .then((m) => m.routes)
  }
];
```

And on my remote I have a routes file `path-one.routes.ts` with routes defined:

```typescript
export const routes: Routes = [
  {
    path: '',
    component: PathOneComponent
  },
  {
    path: 'sub',
    component: PathOneSubComponent
  }
];
```

And this is exposed in my remote's federation config:
```typescript
exposes: {
    './PathOneRoutes': './src/app/path-one/path-one.routes.ts',
  },
```

I don't see the wrapper approach working here, as described in this [article](https://medium.com/@lukas.caniga/angular-17-as-microfrontend-native-federation-supporting-pwa-and-ssr-1e9d43eb411d), because it looks like a solution for loading a single component, and not a route tree.

**Comment by PaulDMooney** [comment]
Bump: Is there, or will there be a way to use SSR when loading up remote routes or route modules as described in my last comment?

So far, everything mentioned seems to me that it's only good for loading components, or elude to how one could implement microsites with their own routing under a given path as microfrontends.
