### ISSUE TITLE
Repost Angular 17.1.* | nf | webComponents

### ISSUE THREAD

**Issue by b34eternus** [angular-architects/module-federation-plugin#565]
Is there a repo example for usage of nf with web components both at angular 17.1.* version?
And is there a way to inherit stylesheet within another host (different repository host)

Proj A

some shared dependency
shell
basic ui
angular1-17v (host)
modules
Proj B - different repo

angular2-legacy (host)
use of 3rd party components with specific styles (imports / custom )
modules
webcomponents

[repost ](https://github.com/manfredsteyer/native-federation-vite-angular-demo/issues/2)

**Comment by manfredsteyer** [comment]
This here is using 17.1 but no web components:
https://github.com/manfredsteyer/module-federation-plugin-example/tree/nf-standalone-solution

However, the web component story did not change, since v16, so all you find in here should be still valid:
https://www.angulararchitects.io/blog/micro-frontends-with-modern-angular-part-2-multi-version-and-multi-framework-solutions-with-angular-elements-and-web-components/
