### ISSUE TITLE
Package subpath './src/builders/application' is not defined by exports ... with Angular 18

### ISSUE THREAD

**Issue by berkon** [angular-architects/module-federation-plugin#583]
When trying to move to Angular 18.0.3 (currently latest) we are getting:

![image](https://github.com/angular-architects/module-federation-plugin/assets/28842661/21a0571a-9ad0-44ea-a73c-17f5409b3f4d)

These are the dependency sections of my package.json:

![image](https://github.com/angular-architects/module-federation-plugin/assets/28842661/a628352e-f310-4159-9966-0dd08bcb39c5)

Npm install runs fine. I'm getting this issue when running ng build.

**Comment by berkon** [comment]
Running a post install script like mentioned here https://github.com/angular-architects/module-federation-plugin/blob/main/libs/native-federation/docs/update18.md seems to be a workaround. But to be honest its nearly impossible to find this hint when searching for the error message. It would be very helpful to put a big reminder in the top level Readme of the repo, as long as the patch is required.

**Comment by gilliamroelofs** [comment]
I have a couple of questions:

1. The documentation mentions that the post-install script is a temporary solution and won't be necessary in future versions. Is there any clarity on when this will be resolved?

2. The file [src/builders/build/builder.ts](https://github.com/angular-architects/module-federation-plugin/blob/main/libs/native-federation/src/builders/build/builder.ts) seems to reuse private functions from Angular's build functions. Am I correct that for this reason the package.json needs to be changed? Is there a way we can avoid this because the @angular/build package does not have to take breaking changes into account for these functions

**Comment by manfredsteyer** [comment]
Hi @gilliamroelofs,

1. We need to land a PR (basically 2 lines of code) in the Angular CLI. We are already in contact with the CLI team.
2. Once this PR is landed, we will have an official way of using the parts of the CLI we need. One of our goals is to be as close to the CLI as possible. Hence, we don't implement these parts by ourselves.
