### ISSUE TITLE
Cannot run ng add for packages requiring bootstrap

### ISSUE THREAD

**Issue by Aeseir** [angular-architects/module-federation-plugin#64]
If you run **ng add _SomePackage_ --project _Project_** on a project that has module-federation-plugin installed it fails with following  **Bootstrap call not found**.

Steps to reproduce:
 * Create new workspace
 * Create a shell and mfe1 project using **ng generate app**
 * Install module-federation-plugin for both
    * ng add @angular-architects/module-federation@latest --project shell -port 5000
    * ng add @angular-architects/module-federation@latest --project mfe1 -port 3000
 * Try adding angular material package using ng approach
    * ng add @angular/material --project shell
    * Choose your fav theme
    * Choose Yes for Global Typography and Browser Animations
 * Installation breaks 

Example output:

![image](https://user-images.githubusercontent.com/985321/124589300-2f50fa80-de9d-11eb-8d07-fa88b6f613e3.png)

The problem stems from fact that bootstrap code below:

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
```

Has been moved out of main.ts and into bootstrap.ts, so the installation then fails. I've tested it with a project that didn't have module-fed-plugin installed and it worked as bootstrap is located in main.ts.

While there is a workaround, the problem with this is you have to account for packages that potentially may need bootstrap present in the main.ts file.

**Comment by manfredsteyer** [comment]
Yes, this is kind of a hen/egg issue. MF needs "async bootstrapping" and we can accomplish this by a main.ts with a dynamic import pointing to another file that bootstraps Angular. On the other side, some schematics from the Angular team expect that the main already contains the bootstrap call. They use it to identify your AppModule.

In the latest version of the MF plugin, you can temporarily turn off async bootstrapping:

ng g @angular-architects/module-federation:boot-async false --project myProject
Run your schematic, e. g. ng add @angular/material
ng g @angular-architects/module-federation:boot-async true --project myProject

Don't forget to turn it on again. Otherwise, MF will very likely crash ...
