### ISSUE TITLE
Using Different Angular Minor Versions (Host 17.3.0 vs. Remote 17.2.0) Causes Inject Error

### ISSUE THREAD

**Issue by vtecc64** [angular-architects/module-federation-plugin#717]
### For which library do you need help?

module-federation

### Question

Hi everyone,

We’re using Angular Module Federation with a host and a remote, both on Angular 17. However, our host (~17.3.0) is on a faster release cycle (will soon be upgraded to 18) while our remote (~17.2.0) is maintained by a larger company, which has longer update cycles. Attempting to run these two versions together triggers the well known inject error:

`ERROR RuntimeError: NG0203: inject() must be called from an injection context...`

Is there a recommended approach to handle minor and major version differences using Module Federation? Should we switch entirely to Native Federation? Any guidance would be greatly appreciated.

Thank you in advance for your help!

**Comment by manfredsteyer** [comment]
Hi,

Yes, this is a known limitation. If an application was compiled with a specific Angular version, it expects to see the same version at runtime. The reason is that the compiled application uses Angular's private API, and there are no guarantees for private APIs in terms of server. Even a different patch version can cause this issue.

There are signs that future Angular versions might come with some guarantees for this.

So, currently, either you ensure that you have precisely the same version everywhere, or you need to go with a multi-version approach like described here [1].

Best wishes,
Manfred

[1] https://www.angulararchitects.io/blog/micro-frontends-with-modern-angular-part-2-multi-version-and-multi-framework-solutions-with-angular-elements-and-web-components/
